'use client';

import React, { useState } from 'react';
import './globals.css';
import { Montserrat } from 'next/font/google';

import MainExpandedNavbar from '@/components/main-components/navbars/MainExpandedNavbar';
import MainNavbar from '../components/main-components/navbars/MainNavbar';

const montserrat = Montserrat({ subsets: ['latin'] });

// export const metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app'
// };

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	const [isNavbarExpanded, setIsNavbarExpanded] = useState(false);

	return (
		<html lang="en">
			<body className={`${montserrat.className},  overflow-x-hidden bg-mainBg`}>
				{isNavbarExpanded ? (
					<MainExpandedNavbar onClose={() => setIsNavbarExpanded(false)} />
				) : (
					<MainNavbar onExpand={() => setIsNavbarExpanded(true)} />
				)}
				{children}
			</body>
		</html>
	);
}
