import './globals.css';
import { Inter } from 'next/font/google';
import MainExpandedNavbar from '@/components/main-components/navbars/MainExpandedNavbar';
// import { useClient } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	// useClient();
	return (
		<html lang="en">
			<body className={inter.className}>
				<MainExpandedNavbar />
				{children}
			</body>
		</html>
	);
}
